In [1]:
import numpy as np

In [10]:
x = np.array([3,4,5])
y = np.array([6,7,8])

In [3]:
x + y

array([ 9, 11, 13])

In [11]:
x = np.array([[1,2], [3,4]])

print(x)

[[1 2]
 [3 4]]


In [12]:
x.ndim

2

In [13]:
x.dtype

dtype('int64')

In [17]:
x = np.array([1,2,3,4])
print(np.sum(x))

10


In [19]:
x = np.array([1, 2, 3, 4, 5, 6])
print(x)
x_reshape = x.reshape((2, 3))
print(x_reshape)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [20]:
x_reshape[0, 0]

1

In [22]:
x_reshape[1,2]

6

In [23]:
x_reshape.shape, x_reshape.ndim, x_reshape.T

((2, 3),
 2,
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [24]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [25]:
x**2

array([ 1,  4,  9, 16, 25, 36])

In [26]:
x**0.5

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [27]:
x = np.random.normal(size = 50)
x

array([ 1.2060759 , -0.8635006 , -0.17152294, -0.80241443,  0.51536357,
        0.56257423,  0.87761188, -0.4811925 , -0.20360061,  0.3233899 ,
        0.10793073,  1.47870977,  1.0111371 , -0.68928031,  1.27210091,
       -0.12222842,  1.14387609, -1.53466944, -0.7879506 , -0.21969634,
        0.3979885 ,  0.97412388, -0.26722789, -0.78043081,  0.28627115,
       -0.8899238 ,  0.15381586,  0.88138685, -0.5414641 ,  0.0079402 ,
        0.17536867, -0.34958778,  0.74272321,  0.77496999, -2.27075568,
       -0.30989925,  0.83371403, -0.315808  , -0.16714879,  1.22547209,
        0.39641406,  0.06417772,  0.69214208, -0.10542267,  1.39448381,
        0.61920858, -0.38541457,  1.29689735, -1.82568648, -1.11685234])